/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// AgeRatingCategoryEnums : The organization that has issued a specific rating   1: ESRB   2: PEGI   3: CERO   4: USK   5: GRAC   6: CLASS_IND   7: ACB   
/// The organization that has issued a specific rating   1: ESRB   2: PEGI   3: CERO   4: USK   5: GRAC   6: CLASS_IND   7: ACB   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum AgeRatingCategoryEnums {
    ESRB = 1,
    PEGI = 2,
    CERO = 3,
    USK = 4,
    GRAC = 5,
    CLASS_IND = 6,
    ACB = 7,

}

impl std::fmt::Display for AgeRatingCategoryEnums {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::ESRB => "1",
            Self::PEGI => "2",
            Self::CERO => "3",
            Self::USK => "4",
            Self::GRAC => "5",
            Self::CLASS_IND => "6",
            Self::ACB => "7",
        })
    }
}
impl Default for AgeRatingCategoryEnums {
    fn default() -> AgeRatingCategoryEnums {
        Self::ESRB
    }
}

