/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgeRatingCategory : The rating category from the organization
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgeRatingCategory {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The rating name
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<i32>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl AgeRatingCategory {
    /// The rating category from the organization
    pub fn new() -> AgeRatingCategory {
        AgeRatingCategory {
            id: None,
            rating: None,
            organization: None,
            updated_at: None,
            created_at: None,
            checksum: None,
        }
    }
}

