/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgeRating {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<models::AgeRatingCategoryEnums>,
    /// Array of Age Rating Content Description IDs
    #[serde(rename = "content_descriptions", skip_serializing_if = "Option::is_none")]
    pub content_descriptions: Option<Vec<models::Id>>,
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<models::AgeRatingEnums>,
    #[serde(rename = "rating_category", skip_serializing_if = "Option::is_none")]
    pub rating_category: Option<Box<models::AgeRatingCategory>>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Box<models::AgeRatingOrganization>>,
    /// The url for the image of an age rating
    #[serde(rename = "rating_cover_url", skip_serializing_if = "Option::is_none")]
    pub rating_cover_url: Option<String>,
    /// A free text motivating a rating
    #[serde(rename = "synopsis", skip_serializing_if = "Option::is_none")]
    pub synopsis: Option<String>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl AgeRating {
    pub fn new() -> AgeRating {
        AgeRating {
            id: None,
            category: None,
            content_descriptions: None,
            rating: None,
            rating_category: None,
            organization: None,
            rating_cover_url: None,
            synopsis: None,
            checksum: None,
        }
    }
}

