/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// AgeRatingEnums : The age rating assigned by the organization   1: Three   2: Seven   3: Twelve   4: Sixteen   5: Eighteen   6: RP   7: EC   8: E   9: E10   10: T   11: M   12: AO   13: CERO_A   14: CERO_B   15: CERO_C   16: CERO_D   17: CERO_Z   18: USK_0   19: USK_6   20: USK_12   21: USK_16   22: USK_18   23: GRAC_ALL   24: GRAC_Twelve   25: GRAC_Fifteen   26: GRAC_Eighteen   27: GRAC_TESTING   28: CLASS_IND_L   29: CLASS_IND_Ten   30: CLASS_IND_Twelve   31: CLASS_IND_Fourteen   32: CLASS_IND_Sixteen   33: CLASS_IND_Eighteen   34: ACB_G   35: ACB_PG   36: ACB_M   37: ACB_MA15   38: ACB_R18   39: ACB_RC   
/// The age rating assigned by the organization   1: Three   2: Seven   3: Twelve   4: Sixteen   5: Eighteen   6: RP   7: EC   8: E   9: E10   10: T   11: M   12: AO   13: CERO_A   14: CERO_B   15: CERO_C   16: CERO_D   17: CERO_Z   18: USK_0   19: USK_6   20: USK_12   21: USK_16   22: USK_18   23: GRAC_ALL   24: GRAC_Twelve   25: GRAC_Fifteen   26: GRAC_Eighteen   27: GRAC_TESTING   28: CLASS_IND_L   29: CLASS_IND_Ten   30: CLASS_IND_Twelve   31: CLASS_IND_Fourteen   32: CLASS_IND_Sixteen   33: CLASS_IND_Eighteen   34: ACB_G   35: ACB_PG   36: ACB_M   37: ACB_MA15   38: ACB_R18   39: ACB_RC   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum AgeRatingEnums {
    Three = 1,
    Seven = 2,
    Twelve = 3,
    Sixteen = 4,
    Eighteen = 5,
    RP = 6,
    EC = 7,
    E = 8,
    E10 = 9,
    T = 10,
    M = 11,
    AO = 12,
    CERO_A = 13,
    CERO_B = 14,
    CERO_C = 15,
    CERO_D = 16,
    CERO_Z = 17,
    USK_0 = 18,
    USK_6 = 19,
    USK_12 = 20,
    USK_16 = 21,
    USK_18 = 22,
    GRAC_ALL = 23,
    GRAC_Twelve = 24,
    GRAC_Fifteen = 25,
    GRAC_Eighteen = 26,
    GRAC_TESTING = 27,
    CLASS_IND_L = 28,
    CLASS_IND_Ten = 29,
    CLASS_IND_Twelve = 30,
    CLASS_IND_Fourteen = 31,
    CLASS_IND_Sixteen = 32,
    CLASS_IND_Eighteen = 33,
    ACB_G = 34,
    ACB_PG = 35,
    ACB_M = 36,
    ACB_MA15 = 37,
    ACB_R18 = 38,
    ACB_RC = 39,

}

impl std::fmt::Display for AgeRatingEnums {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Three => "1",
            Self::Seven => "2",
            Self::Twelve => "3",
            Self::Sixteen => "4",
            Self::Eighteen => "5",
            Self::RP => "6",
            Self::EC => "7",
            Self::E => "8",
            Self::E10 => "9",
            Self::T => "10",
            Self::M => "11",
            Self::AO => "12",
            Self::CERO_A => "13",
            Self::CERO_B => "14",
            Self::CERO_C => "15",
            Self::CERO_D => "16",
            Self::CERO_Z => "17",
            Self::USK_0 => "18",
            Self::USK_6 => "19",
            Self::USK_12 => "20",
            Self::USK_16 => "21",
            Self::USK_18 => "22",
            Self::GRAC_ALL => "23",
            Self::GRAC_Twelve => "24",
            Self::GRAC_Fifteen => "25",
            Self::GRAC_Eighteen => "26",
            Self::GRAC_TESTING => "27",
            Self::CLASS_IND_L => "28",
            Self::CLASS_IND_Ten => "29",
            Self::CLASS_IND_Twelve => "30",
            Self::CLASS_IND_Fourteen => "31",
            Self::CLASS_IND_Sixteen => "32",
            Self::CLASS_IND_Eighteen => "33",
            Self::ACB_G => "34",
            Self::ACB_PG => "35",
            Self::ACB_M => "36",
            Self::ACB_MA15 => "37",
            Self::ACB_R18 => "38",
            Self::ACB_RC => "39",
        })
    }
}
impl Default for AgeRatingEnums {
    fn default() -> AgeRatingEnums {
        Self::Three
    }
}

