/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// CharacterGenderEnum : An Enum of the character's gender   0: Male   1: Female   2: Other   
/// An Enum of the character's gender   0: Male   1: Female   2: Other   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum CharacterGenderEnum {
    Male = 0,
    Female = 1,
    Other = 2,

}

impl std::fmt::Display for CharacterGenderEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Male => "0",
            Self::Female => "1",
            Self::Other => "2",
        })
    }
}
impl Default for CharacterGenderEnum {
    fn default() -> CharacterGenderEnum {
        Self::Male
    }
}

