/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Character : Video game characters
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Character {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Alternative names for a character
    #[serde(rename = "akas", skip_serializing_if = "Option::is_none")]
    pub akas: Option<Vec<String>>,
    /// A Character's country of origin
    #[serde(rename = "country_name", skip_serializing_if = "Option::is_none")]
    pub country_name: Option<String>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// Text describing a character
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "games", skip_serializing_if = "Option::is_none")]
    pub games: Option<Vec<models::Id>>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<models::CharacterGenderEnum>,
    /// The IGDB object unique identifier
    #[serde(rename = "character_gender", skip_serializing_if = "Option::is_none")]
    pub character_gender: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "mug_shot", skip_serializing_if = "Option::is_none")]
    pub mug_shot: Option<i32>,
    /// The character's name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A url-safe, unique, lower-case version of the name
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "species", skip_serializing_if = "Option::is_none")]
    pub species: Option<models::CharacterSpeciesEnum>,
    /// The IGDB object unique identifier
    #[serde(rename = "character_species", skip_serializing_if = "Option::is_none")]
    pub character_species: Option<i32>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// The website address (URL) of the item
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl Character {
    /// Video game characters
    pub fn new() -> Character {
        Character {
            id: None,
            akas: None,
            country_name: None,
            created_at: None,
            description: None,
            games: None,
            gender: None,
            character_gender: None,
            mug_shot: None,
            name: None,
            slug: None,
            species: None,
            character_species: None,
            updated_at: None,
            url: None,
            checksum: None,
        }
    }
}

