/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// CharacterSpeciesEnum : An enum of the Character's species   1: Human   2: Alien   3: Animal   
/// An enum of the Character's species   1: Human   2: Alien   3: Animal   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum CharacterSpeciesEnum {
    Human = 1,
    Alien = 2,
    Animal = 3,

}

impl std::fmt::Display for CharacterSpeciesEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Human => "1",
            Self::Alien => "2",
            Self::Animal => "3",
        })
    }
}
impl Default for CharacterSpeciesEnum {
    fn default() -> CharacterSpeciesEnum {
        Self::Human
    }
}

