/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Collection : Collection, AKA Series
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Collection {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "as_child_relations", skip_serializing_if = "Option::is_none")]
    pub as_child_relations: Option<Vec<models::Id>>,
    #[serde(rename = "as_parent_relations", skip_serializing_if = "Option::is_none")]
    pub as_parent_relations: Option<Vec<models::Id>>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    #[serde(rename = "games", skip_serializing_if = "Option::is_none")]
    pub games: Option<Vec<models::Id>>,
    /// Umbrella term for a collection of games
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A url-safe, unique, lower-case version of the name
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// The website address (URL) of the item
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl Collection {
    /// Collection, AKA Series
    pub fn new() -> Collection {
        Collection {
            id: None,
            as_child_relations: None,
            as_parent_relations: None,
            created_at: None,
            games: None,
            name: None,
            slug: None,
            r#type: None,
            updated_at: None,
            url: None,
            checksum: None,
        }
    }
}

