/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CollectionRelation : Describes relationship between collections
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionRelation {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "child_collection", skip_serializing_if = "Option::is_none")]
    pub child_collection: Option<i32>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The IGDB object unique identifier
    #[serde(rename = "parent_collection", skip_serializing_if = "Option::is_none")]
    pub parent_collection: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl CollectionRelation {
    /// Describes relationship between collections
    pub fn new() -> CollectionRelation {
        CollectionRelation {
            id: None,
            child_collection: None,
            created_at: None,
            parent_collection: None,
            r#type: None,
            updated_at: None,
            checksum: None,
        }
    }
}

