/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Company : Video game companies, both publishers and developers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Company {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "change_date_category", skip_serializing_if = "Option::is_none")]
    pub change_date_category: Option<models::ChangeDateCategoryEnum>,
    /// The IGDB object unique identifier
    #[serde(rename = "change_date_format", skip_serializing_if = "Option::is_none")]
    pub change_date_format: Option<i32>,
    /// The date when a compnay got a new ID
    #[serde(rename = "change_date", skip_serializing_if = "Option::is_none")]
    pub change_date: Option<i64>,
    /// The new ID for a company that has gone through a merger or restructuring
    #[serde(rename = "changed_company_id", skip_serializing_if = "Option::is_none")]
    pub changed_company_id: Option<String>,
    /// ISO 3166-1 numeric country code
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<i32>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// A free text description of the company
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "developed", skip_serializing_if = "Option::is_none")]
    pub developed: Option<Vec<models::Id>>,
    /// The IGDB object unique identifier
    #[serde(rename = "logo", skip_serializing_if = "Option::is_none")]
    pub logo: Option<i32>,
    /// The name of the company
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<i32>,
    #[serde(rename = "published", skip_serializing_if = "Option::is_none")]
    pub published: Option<Vec<models::Id>>,
    /// A url-safe, unique, lower-case version of the name
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The date that the company was founded
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<i64>,
    #[serde(rename = "start_date_category", skip_serializing_if = "Option::is_none")]
    pub start_date_category: Option<models::StartDateCategoryEnum>,
    /// The IGDB object unique identifier
    #[serde(rename = "start_date_format", skip_serializing_if = "Option::is_none")]
    pub start_date_format: Option<i32>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// The website address (URL) of the item
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "websites", skip_serializing_if = "Option::is_none")]
    pub websites: Option<Vec<models::Id>>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl Company {
    /// Video game companies, both publishers and developers
    pub fn new() -> Company {
        Company {
            id: None,
            change_date_category: None,
            change_date_format: None,
            change_date: None,
            changed_company_id: None,
            country: None,
            created_at: None,
            description: None,
            developed: None,
            logo: None,
            name: None,
            parent: None,
            published: None,
            slug: None,
            start_date: None,
            start_date_category: None,
            start_date_format: None,
            updated_at: None,
            url: None,
            websites: None,
            checksum: None,
        }
    }
}

