/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Event : Gaming events like GamesCom, Tokyo Game Show, PAX, or GSL
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The name of the event
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The description of the event
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A url-safe, unique, lower-case version of the name
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "event_logo", skip_serializing_if = "Option::is_none")]
    pub event_logo: Option<i32>,
    /// Start time of the event in UTC
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
    /// End time of the event in UTC
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i64>,
    /// Timezone the event is in.
    #[serde(rename = "time_zone", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
    /// URL to the livestream of the event.
    #[serde(rename = "live_stream_url", skip_serializing_if = "Option::is_none")]
    pub live_stream_url: Option<String>,
    #[serde(rename = "games", skip_serializing_if = "Option::is_none")]
    pub games: Option<Vec<models::Id>>,
    #[serde(rename = "videos", skip_serializing_if = "Option::is_none")]
    pub videos: Option<Vec<models::Id>>,
    #[serde(rename = "event_networks", skip_serializing_if = "Option::is_none")]
    pub event_networks: Option<Vec<models::Id>>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl Event {
    /// Gaming events like GamesCom, Tokyo Game Show, PAX, or GSL
    pub fn new() -> Event {
        Event {
            id: None,
            name: None,
            description: None,
            slug: None,
            event_logo: None,
            start_time: None,
            end_time: None,
            time_zone: None,
            live_stream_url: None,
            games: None,
            videos: None,
            event_networks: None,
            created_at: None,
            updated_at: None,
            checksum: None,
        }
    }
}

