/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// ExternalGameCategoryEnums : The external platform the game is on   1: steam   5: gog   10: youtube   11: microsoft   13: apple   14: twitch   15: android   20: amazon_asin   22: amazon_luna   23: amazon_adg   26: epic_game_store   28: oculus   29: utomik   30: itch_io   31: xbox_marketplace   32: kartridge   36: playstation_store_us   37: focus_entertainment   54: xbox_game_pass_ultimate_cloud   55: gamejolt   
/// The external platform the game is on   1: steam   5: gog   10: youtube   11: microsoft   13: apple   14: twitch   15: android   20: amazon_asin   22: amazon_luna   23: amazon_adg   26: epic_game_store   28: oculus   29: utomik   30: itch_io   31: xbox_marketplace   32: kartridge   36: playstation_store_us   37: focus_entertainment   54: xbox_game_pass_ultimate_cloud   55: gamejolt   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum ExternalGameCategoryEnums {
    steam = 1,
    gog = 5,
    youtube = 10,
    microsoft = 11,
    apple = 13,
    twitch = 14,
    android = 15,
    amazon_asin = 20,
    amazon_luna = 22,
    amazon_adg = 23,
    epic_game_store = 26,
    oculus = 28,
    utomik = 29,
    itch_io = 30,
    xbox_marketplace = 31,
    kartridge = 32,
    playstation_store_us = 36,
    focus_entertainment = 37,
    xbox_game_pass_ultimate_cloud = 54,
    gamejolt = 55,

}

impl std::fmt::Display for ExternalGameCategoryEnums {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::steam => "1",
            Self::gog => "5",
            Self::youtube => "10",
            Self::microsoft => "11",
            Self::apple => "13",
            Self::twitch => "14",
            Self::android => "15",
            Self::amazon_asin => "20",
            Self::amazon_luna => "22",
            Self::amazon_adg => "23",
            Self::epic_game_store => "26",
            Self::oculus => "28",
            Self::utomik => "29",
            Self::itch_io => "30",
            Self::xbox_marketplace => "31",
            Self::kartridge => "32",
            Self::playstation_store_us => "36",
            Self::focus_entertainment => "37",
            Self::xbox_game_pass_ultimate_cloud => "54",
            Self::gamejolt => "55",
        })
    }
}
impl Default for ExternalGameCategoryEnums {
    fn default() -> ExternalGameCategoryEnums {
        Self::steam
    }
}

