/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExternalGame : Game IDs on other services
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalGame {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<models::ExternalGameCategoryEnums>,
    /// The IGDB object unique identifier
    #[serde(rename = "external_game_source", skip_serializing_if = "Option::is_none")]
    pub external_game_source: Option<i32>,
    /// The ISO country code of the external game product.
    #[serde(rename = "countries", skip_serializing_if = "Option::is_none")]
    pub countries: Option<Vec<i32>>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The IGDB object unique identifier
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<i32>,
    #[serde(rename = "media", skip_serializing_if = "Option::is_none")]
    pub media: Option<models::ExternalGameMediaEnums>,
    /// The IGDB object unique identifier
    #[serde(rename = "game_release_format", skip_serializing_if = "Option::is_none")]
    pub game_release_format: Option<i32>,
    /// The name of the game according to the other service
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<i32>,
    /// The other services ID for this game
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// The website address (URL) of the item
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The year in full (2018)
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i32>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl ExternalGame {
    /// Game IDs on other services
    pub fn new() -> ExternalGame {
        ExternalGame {
            id: None,
            category: None,
            external_game_source: None,
            countries: None,
            created_at: None,
            game: None,
            media: None,
            game_release_format: None,
            name: None,
            platform: None,
            uid: None,
            updated_at: None,
            url: None,
            year: None,
            checksum: None,
        }
    }
}

