/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GameVersion : Details about game editions and versions. (DLC and more)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameVersion {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// Features and descriptions of what makes each version/edition different from the main game
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<models::Id>>,
    /// The IGDB object unique identifier
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<i32>,
    /// Game Versions and Editions
    #[serde(rename = "games", skip_serializing_if = "Option::is_none")]
    pub games: Option<Vec<models::Id>>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// The website address (URL) of the item
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl GameVersion {
    /// Details about game editions and versions. (DLC and more)
    pub fn new() -> GameVersion {
        GameVersion {
            id: None,
            created_at: None,
            features: None,
            game: None,
            games: None,
            updated_at: None,
            url: None,
            checksum: None,
        }
    }
}

