/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GameVersionFeatureValue : The bool/text value of the feature
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameVersionFeatureValue {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "game_feature", skip_serializing_if = "Option::is_none")]
    pub game_feature: Option<i32>,
    #[serde(rename = "included_feature", skip_serializing_if = "Option::is_none")]
    pub included_feature: Option<models::GameVersionIncludedFeatureEnums>,
    /// The text value of this feature
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl GameVersionFeatureValue {
    /// The bool/text value of the feature
    pub fn new() -> GameVersionFeatureValue {
        GameVersionFeatureValue {
            id: None,
            game: None,
            game_feature: None,
            included_feature: None,
            note: None,
            checksum: None,
        }
    }
}

