/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GameTimeToBeat : Average time to beat times for a game.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameTimeToBeat {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "game_id", skip_serializing_if = "Option::is_none")]
    pub game_id: Option<i32>,
    /// Average time (in seconds) to finish the game to its credits without spending notable time on extras such as side quests.
    #[serde(rename = "hastily", skip_serializing_if = "Option::is_none")]
    pub hastily: Option<i32>,
    /// Average time (in seconds) to finish the game while mixing in some extras such as side quests without being overly thorough.
    #[serde(rename = "normally", skip_serializing_if = "Option::is_none")]
    pub normally: Option<i32>,
    /// Average time (in seconds) to finish the game to 100% completion.
    #[serde(rename = "completely", skip_serializing_if = "Option::is_none")]
    pub completely: Option<i32>,
    /// Total number of time to beat submissions for this game
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl GameTimeToBeat {
    /// Average time to beat times for a game.
    pub fn new() -> GameTimeToBeat {
        GameTimeToBeat {
            id: None,
            game_id: None,
            hastily: None,
            normally: None,
            completely: None,
            count: None,
            created_at: None,
            updated_at: None,
            checksum: None,
        }
    }
}

