/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Games : Video Games!
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Games {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "age_ratings", skip_serializing_if = "Option::is_none")]
    pub age_ratings: Option<Vec<models::AgeRatingEnums>>,
    /// Rating based on external critic scores
    #[serde(rename = "aggregated_rating", skip_serializing_if = "Option::is_none")]
    pub aggregated_rating: Option<f64>,
    /// Number of external critic scores
    #[serde(rename = "aggregated_rating_count", skip_serializing_if = "Option::is_none")]
    pub aggregated_rating_count: Option<i32>,
    #[serde(rename = "alternative_names", skip_serializing_if = "Option::is_none")]
    pub alternative_names: Option<Vec<models::Id>>,
    #[serde(rename = "artworks", skip_serializing_if = "Option::is_none")]
    pub artworks: Option<Vec<models::Id>>,
    #[serde(rename = "bundles", skip_serializing_if = "Option::is_none")]
    pub bundles: Option<Vec<models::Id>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<models::GameCategoryEnums>,
    /// The IGDB object unique identifier
    #[serde(rename = "game_type", skip_serializing_if = "Option::is_none")]
    pub game_type: Option<i32>,
    #[serde(rename = "collections", skip_serializing_if = "Option::is_none")]
    pub collections: Option<Vec<models::Id>>,
    /// The IGDB object unique identifier
    #[serde(rename = "cover", skip_serializing_if = "Option::is_none")]
    pub cover: Option<i32>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    #[serde(rename = "dlcs", skip_serializing_if = "Option::is_none")]
    pub dlcs: Option<Vec<models::Id>>,
    #[serde(rename = "expanded_games", skip_serializing_if = "Option::is_none")]
    pub expanded_games: Option<Vec<models::Id>>,
    #[serde(rename = "expansions", skip_serializing_if = "Option::is_none")]
    pub expansions: Option<Vec<models::Id>>,
    #[serde(rename = "external_games", skip_serializing_if = "Option::is_none")]
    pub external_games: Option<Vec<models::Id>>,
    /// The first release date for this game
    #[serde(rename = "first_release_date", skip_serializing_if = "Option::is_none")]
    pub first_release_date: Option<i64>,
    #[serde(rename = "forks", skip_serializing_if = "Option::is_none")]
    pub forks: Option<Vec<models::Id>>,
    /// The main franchise
    #[serde(rename = "franchise", skip_serializing_if = "Option::is_none")]
    pub franchise: Option<String>,
    /// Other franchises the game belongs to
    #[serde(rename = "franchises", skip_serializing_if = "Option::is_none")]
    pub franchises: Option<Vec<models::Id>>,
    /// The game engine used in this game
    #[serde(rename = "game_engines", skip_serializing_if = "Option::is_none")]
    pub game_engines: Option<Vec<models::Id>>,
    /// Supported game localizations for this game. A region can have at most one game localization for a given game
    #[serde(rename = "game_localizations", skip_serializing_if = "Option::is_none")]
    pub game_localizations: Option<Vec<models::Id>>,
    /// Modes of gameplay
    #[serde(rename = "game_modes", skip_serializing_if = "Option::is_none")]
    pub game_modes: Option<Vec<models::Id>>,
    /// Genres of the game
    #[serde(rename = "genres", skip_serializing_if = "Option::is_none")]
    pub genres: Option<Vec<models::Id>>,
    /// Number of follows a game gets before release
    #[serde(rename = "hypes", skip_serializing_if = "Option::is_none")]
    pub hypes: Option<i32>,
    /// Companies who developed this game
    #[serde(rename = "involved_companies", skip_serializing_if = "Option::is_none")]
    pub involved_companies: Option<Vec<models::Id>>,
    /// Associated keywords
    #[serde(rename = "keywords", skip_serializing_if = "Option::is_none")]
    pub keywords: Option<Vec<models::Id>>,
    /// Supported Languages for this game
    #[serde(rename = "language_supports", skip_serializing_if = "Option::is_none")]
    pub language_supports: Option<Vec<models::Id>>,
    /// Multiplayer modes for this game
    #[serde(rename = "multiplayer_modes", skip_serializing_if = "Option::is_none")]
    pub multiplayer_modes: Option<Vec<models::Id>>,
    /// The name of the Game
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "parent_game", skip_serializing_if = "Option::is_none")]
    pub parent_game: Option<i32>,
    /// Platforms this game was released on
    #[serde(rename = "platforms", skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<models::Id>>,
    /// The main perspective of the player
    #[serde(rename = "player_perspectives", skip_serializing_if = "Option::is_none")]
    pub player_perspectives: Option<Vec<models::Id>>,
    /// Ports of this game
    #[serde(rename = "ports", skip_serializing_if = "Option::is_none")]
    pub ports: Option<Vec<models::Id>>,
    /// Average IGDB user rating
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<f64>,
    /// Total number of IGDB user ratings
    #[serde(rename = "rating_count", skip_serializing_if = "Option::is_none")]
    pub rating_count: Option<i32>,
    /// Release dates of this game
    #[serde(rename = "release_dates", skip_serializing_if = "Option::is_none")]
    pub release_dates: Option<Vec<models::Id>>,
    /// Remakes of this game
    #[serde(rename = "remakes", skip_serializing_if = "Option::is_none")]
    pub remakes: Option<Vec<models::Id>>,
    /// Remasters of this game
    #[serde(rename = "remasters", skip_serializing_if = "Option::is_none")]
    pub remasters: Option<Vec<models::Id>>,
    /// Screenshots of this game
    #[serde(rename = "screenshots", skip_serializing_if = "Option::is_none")]
    pub screenshots: Option<Vec<models::Id>>,
    /// Similar games
    #[serde(rename = "similar_games", skip_serializing_if = "Option::is_none")]
    pub similar_games: Option<Vec<models::Id>>,
    /// A url-safe, unique, lower-case version of the name
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// Standalone expansions of this game
    #[serde(rename = "standalone_expansions", skip_serializing_if = "Option::is_none")]
    pub standalone_expansions: Option<Vec<models::Id>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::GameStatusEnums>,
    /// The IGDB object unique identifier
    #[serde(rename = "game_status", skip_serializing_if = "Option::is_none")]
    pub game_status: Option<i32>,
    /// A short description of a games story
    #[serde(rename = "storyline", skip_serializing_if = "Option::is_none")]
    pub storyline: Option<String>,
    /// A description of the game
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// Related entities in the IGDB API
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<i32>>,
    /// Themes of the game
    #[serde(rename = "themes", skip_serializing_if = "Option::is_none")]
    pub themes: Option<Vec<models::Id>>,
    /// Average rating based on both IGDB user and external critic scores
    #[serde(rename = "total_rating", skip_serializing_if = "Option::is_none")]
    pub total_rating: Option<f64>,
    /// Total number of user and external critic scores
    #[serde(rename = "total_rating_count", skip_serializing_if = "Option::is_none")]
    pub total_rating_count: Option<i32>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// The website address (URL) of the item
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// If a version, this is the main game
    #[serde(rename = "version_parent", skip_serializing_if = "Option::is_none")]
    pub version_parent: Option<Vec<models::Id>>,
    /// Title of this version (i.e Gold edition)
    #[serde(rename = "version_title", skip_serializing_if = "Option::is_none")]
    pub version_title: Option<String>,
    /// Videos of this game
    #[serde(rename = "videos", skip_serializing_if = "Option::is_none")]
    pub videos: Option<Vec<models::Id>>,
    /// Websites associated with this game
    #[serde(rename = "websites", skip_serializing_if = "Option::is_none")]
    pub websites: Option<Vec<models::Id>>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl Games {
    /// Video Games!
    pub fn new() -> Games {
        Games {
            id: None,
            age_ratings: None,
            aggregated_rating: None,
            aggregated_rating_count: None,
            alternative_names: None,
            artworks: None,
            bundles: None,
            category: None,
            game_type: None,
            collections: None,
            cover: None,
            created_at: None,
            dlcs: None,
            expanded_games: None,
            expansions: None,
            external_games: None,
            first_release_date: None,
            forks: None,
            franchise: None,
            franchises: None,
            game_engines: None,
            game_localizations: None,
            game_modes: None,
            genres: None,
            hypes: None,
            involved_companies: None,
            keywords: None,
            language_supports: None,
            multiplayer_modes: None,
            name: None,
            parent_game: None,
            platforms: None,
            player_perspectives: None,
            ports: None,
            rating: None,
            rating_count: None,
            release_dates: None,
            remakes: None,
            remasters: None,
            screenshots: None,
            similar_games: None,
            slug: None,
            standalone_expansions: None,
            status: None,
            game_status: None,
            storyline: None,
            summary: None,
            tags: None,
            themes: None,
            total_rating: None,
            total_rating_count: None,
            updated_at: None,
            url: None,
            version_parent: None,
            version_title: None,
            videos: None,
            websites: None,
            checksum: None,
        }
    }
}

