/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// GameStatusEnums : A game's operational status   0: released   2: alpha   3: beta   4: early_access   5: offline   6: cancelled   7: rumored   8: delisted   
/// A game's operational status   0: released   2: alpha   3: beta   4: early_access   5: offline   6: cancelled   7: rumored   8: delisted   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum GameStatusEnums {
    released = 0,
    alpha = 2,
    beta = 3,
    early_access = 4,
    offline = 5,
    cancelled = 6,
    rumored = 7,
    delisted = 8,

}

impl std::fmt::Display for GameStatusEnums {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::released => "0",
            Self::alpha => "2",
            Self::beta => "3",
            Self::early_access => "4",
            Self::offline => "5",
            Self::cancelled => "6",
            Self::rumored => "7",
            Self::delisted => "8",
        })
    }
}
impl Default for GameStatusEnums {
    fn default() -> GameStatusEnums {
        Self::released
    }
}

