/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GameVideo : A video associated with a game
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameVideo {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<i32>,
    /// The name of the video
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The external ID of the video (usually youtube)
    #[serde(rename = "video_id", skip_serializing_if = "Option::is_none")]
    pub video_id: Option<String>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl GameVideo {
    /// A video associated with a game
    pub fn new() -> GameVideo {
        GameVideo {
            id: None,
            game: None,
            name: None,
            video_id: None,
            checksum: None,
        }
    }
}

