/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GameVersionFeatures : Features and descriptions of what makes each version/edition different from the main game
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameVersionFeatures {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<models::GameVersionFeatureCategoryEnums>,
    /// The description of the feature
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Position of this feature in the list of features
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    /// The title of the version/addition/DLC
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The bool/text value of the feature
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<models::Id>>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl GameVersionFeatures {
    /// Features and descriptions of what makes each version/edition different from the main game
    pub fn new() -> GameVersionFeatures {
        GameVersionFeatures {
            id: None,
            category: None,
            description: None,
            position: None,
            title: None,
            values: None,
            checksum: None,
        }
    }
}

