/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// GameVersionIncludedFeatureEnums : The value of this feature   0: NOT_INCLUDED   1: INCLUDED   2: PRE_ORDER_ONLY   
/// The value of this feature   0: NOT_INCLUDED   1: INCLUDED   2: PRE_ORDER_ONLY   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum GameVersionIncludedFeatureEnums {
    not_included = 0,
    included = 1,
    pre_order_only = 2,

}

impl std::fmt::Display for GameVersionIncludedFeatureEnums {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::not_included => "0",
            Self::included => "1",
            Self::pre_order_only => "2",
        })
    }
}
impl Default for GameVersionIncludedFeatureEnums {
    fn default() -> GameVersionIncludedFeatureEnums {
        Self::not_included
    }
}

