/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// GameCategoryEnums : A game's category/catagories   0: main_game   1: dlc_addon   2: expansion   3: bundle   4: standalone_expansion   5: mod   6: episode   7: season   8: remake   9: remaster   10: expanded_game   11: port   12: fork   13: pack   14: update   
/// A game's category/catagories   0: main_game   1: dlc_addon   2: expansion   3: bundle   4: standalone_expansion   5: mod   6: episode   7: season   8: remake   9: remaster   10: expanded_game   11: port   12: fork   13: pack   14: update   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum GameCategoryEnums {
    main_game = 0,
    dlc_addon = 1,
    expansion = 2,
    bundle = 3,
    standalone_expansion = 4,
    #[serde(rename="mod")]
    game_mod = 5,
    episode = 6,
    season = 7,
    remake = 8,
    remaster = 9,
    expanded_game = 10,
    port = 11,
    fork = 12,
    pack = 13,
    update = 14,

}

impl std::fmt::Display for GameCategoryEnums {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::main_game => "0",
            Self::dlc_addon => "1",
            Self::expansion => "2",
            Self::bundle => "3",
            Self::standalone_expansion => "4",
            Self::game_mod => "5",
            Self::episode => "6",
            Self::season => "7",
            Self::remake => "8",
            Self::remaster => "9",
            Self::expanded_game => "10",
            Self::port => "11",
            Self::fork => "12",
            Self::pack => "13",
            Self::update => "14",
        })
    }
}
impl Default for GameCategoryEnums {
    fn default() -> GameCategoryEnums {
        Self::main_game
    }
}

