/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvolvedCompany : Involved companies
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvolvedCompany {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<i32>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// Is the company a/the developer?
    #[serde(rename = "developer", skip_serializing_if = "Option::is_none")]
    pub developer: Option<bool>,
    /// The IGDB object unique identifier
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<i32>,
    /// Did the company port the game?
    #[serde(rename = "porting", skip_serializing_if = "Option::is_none")]
    pub porting: Option<bool>,
    /// Did the company publish the game?
    #[serde(rename = "publisher", skip_serializing_if = "Option::is_none")]
    pub publisher: Option<bool>,
    /// Did the company suppport the game?
    #[serde(rename = "supporting", skip_serializing_if = "Option::is_none")]
    pub supporting: Option<bool>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl InvolvedCompany {
    /// Involved companies
    pub fn new() -> InvolvedCompany {
        InvolvedCompany {
            id: None,
            company: None,
            created_at: None,
            developer: None,
            game: None,
            porting: None,
            publisher: None,
            supporting: None,
            updated_at: None,
            checksum: None,
        }
    }
}

