/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LanguageSupport : Games can be played with different languages for voice acting, subtitles, or the interface language.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LanguageSupport {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "language_support_type", skip_serializing_if = "Option::is_none")]
    pub language_support_type: Option<i32>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl LanguageSupport {
    /// Games can be played with different languages for voice acting, subtitles, or the interface language.
    pub fn new() -> LanguageSupport {
        LanguageSupport {
            id: None,
            game: None,
            language: None,
            language_support_type: None,
            created_at: None,
            updated_at: None,
            checksum: None,
        }
    }
}

