/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MultiplayerMode : Data about the supported multiplayer types
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiplayerMode {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// True if the game supports campaign coop
    #[serde(rename = "camapigncoop", skip_serializing_if = "Option::is_none")]
    pub camapigncoop: Option<bool>,
    /// True if the game supports drop in/out multiplayer
    #[serde(rename = "dropin", skip_serializing_if = "Option::is_none")]
    pub dropin: Option<bool>,
    /// The IGDB object unique identifier
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<i32>,
    /// True if the game supports LAN coop
    #[serde(rename = "lancoop", skip_serializing_if = "Option::is_none")]
    pub lancoop: Option<bool>,
    /// True if the game supports offline coop
    #[serde(rename = "offlinecoop", skip_serializing_if = "Option::is_none")]
    pub offlinecoop: Option<i32>,
    /// Maximum number of offline players in offline coop
    #[serde(rename = "offliencoopmax", skip_serializing_if = "Option::is_none")]
    pub offliencoopmax: Option<i32>,
    /// Maximum number of players in offline multiplayer
    #[serde(rename = "offlinemax", skip_serializing_if = "Option::is_none")]
    pub offlinemax: Option<i32>,
    /// True if the game supports online coop
    #[serde(rename = "onlinecoop", skip_serializing_if = "Option::is_none")]
    pub onlinecoop: Option<bool>,
    /// Maximum number of online players in online coop
    #[serde(rename = "onlinecoopmax", skip_serializing_if = "Option::is_none")]
    pub onlinecoopmax: Option<i32>,
    /// Maximum number of online players in online coop
    #[serde(rename = "onlinemax", skip_serializing_if = "Option::is_none")]
    pub onlinemax: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<i32>,
    /// True if the game supports, split screen, offline multiplayer
    #[serde(rename = "splitscreen", skip_serializing_if = "Option::is_none")]
    pub splitscreen: Option<bool>,
    /// True if the game supports split screen, online multiplayer
    #[serde(rename = "splitscreenonline", skip_serializing_if = "Option::is_none")]
    pub splitscreenonline: Option<bool>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl MultiplayerMode {
    /// Data about the supported multiplayer types
    pub fn new() -> MultiplayerMode {
        MultiplayerMode {
            id: None,
            camapigncoop: None,
            dropin: None,
            game: None,
            lancoop: None,
            offlinecoop: None,
            offliencoopmax: None,
            offlinemax: None,
            onlinecoop: None,
            onlinecoopmax: None,
            onlinemax: None,
            platform: None,
            splitscreen: None,
            splitscreenonline: None,
            checksum: None,
        }
    }
}

