/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NetworkType : Social networks related to the event like twitter, facebook and youtube
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkType {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The name of the social network
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "event_networks", skip_serializing_if = "Option::is_none")]
    pub event_networks: Option<Vec<models::Id>>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl NetworkType {
    /// Social networks related to the event like twitter, facebook and youtube
    pub fn new() -> NetworkType {
        NetworkType {
            id: None,
            name: None,
            event_networks: None,
            created_at: None,
            updated_at: None,
            checksum: None,
        }
    }
}

