/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Platform : The hardware used to run the game or game delivery network
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Platform {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// An abbreviation of the platform name
    #[serde(rename = "abbreviation", skip_serializing_if = "Option::is_none")]
    pub abbreviation: Option<String>,
    /// An alternative name for the platform
    #[serde(rename = "alternative_name", skip_serializing_if = "Option::is_none")]
    pub alternative_name: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<models::PlatformCategoryEnums>,
    /// The IGDB object unique identifier
    #[serde(rename = "platform_type", skip_serializing_if = "Option::is_none")]
    pub platform_type: Option<i32>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The generation of the platform
    #[serde(rename = "generation", skip_serializing_if = "Option::is_none")]
    pub generation: Option<i32>,
    /// The name of the platform
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "platform_family", skip_serializing_if = "Option::is_none")]
    pub platform_family: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "platform_logo", skip_serializing_if = "Option::is_none")]
    pub platform_logo: Option<i32>,
    /// A url-safe, unique, lower-case version of the name
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The summary of the first Version of this platform
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// The website address (URL) of the item
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<models::Id>>,
    #[serde(rename = "websites", skip_serializing_if = "Option::is_none")]
    pub websites: Option<Vec<models::Id>>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl Platform {
    /// The hardware used to run the game or game delivery network
    pub fn new() -> Platform {
        Platform {
            id: None,
            abbreviation: None,
            alternative_name: None,
            category: None,
            platform_type: None,
            created_at: None,
            generation: None,
            name: None,
            platform_family: None,
            platform_logo: None,
            slug: None,
            summary: None,
            updated_at: None,
            url: None,
            versions: None,
            websites: None,
            checksum: None,
        }
    }
}

