/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformVersionCompany : A platform developer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformVersionCompany {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Any notable comments about the developer
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<i32>,
    /// If the company is the developer
    #[serde(rename = "developer", skip_serializing_if = "Option::is_none")]
    pub developer: Option<bool>,
    /// If the company is the manufactuer
    #[serde(rename = "manufacturer", skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<bool>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl PlatformVersionCompany {
    /// A platform developer
    pub fn new() -> PlatformVersionCompany {
        PlatformVersionCompany {
            id: None,
            comment: None,
            company: None,
            developer: None,
            manufacturer: None,
            checksum: None,
        }
    }
}

