/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformVersion : The specific platform and the specifications (Xbox Series X, Playstation 5)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformVersion {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "companies", skip_serializing_if = "Option::is_none")]
    pub companies: Option<Vec<models::Id>>,
    /// The network capabilities
    #[serde(rename = "connectivity", skip_serializing_if = "Option::is_none")]
    pub connectivity: Option<String>,
    /// The integrated central processing unit
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<String>,
    /// The graphics chipset
    #[serde(rename = "graphics", skip_serializing_if = "Option::is_none")]
    pub graphics: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "main_manufacturer", skip_serializing_if = "Option::is_none")]
    pub main_manufacturer: Option<i32>,
    /// The type of media this version accepts
    #[serde(rename = "media", skip_serializing_if = "Option::is_none")]
    pub media: Option<String>,
    /// How much memory there is
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<String>,
    /// The name of the platform version
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The online service, like Xbox Live
    #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
    pub online: Option<String>,
    /// The operating system installed on the platform version
    #[serde(rename = "os", skip_serializing_if = "Option::is_none")]
    pub os: Option<String>,
    /// The output video rate
    #[serde(rename = "output", skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "platform_logo", skip_serializing_if = "Option::is_none")]
    pub platform_logo: Option<i32>,
    #[serde(rename = "platform_version_release_dates", skip_serializing_if = "Option::is_none")]
    pub platform_version_release_dates: Option<Vec<models::Id>>,
    /// The maximum resolution
    #[serde(rename = "resolutions", skip_serializing_if = "Option::is_none")]
    pub resolutions: Option<String>,
    /// A url-safe, unique, lower-case version of the name
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// The sound chipset
    #[serde(rename = "sound", skip_serializing_if = "Option::is_none")]
    pub sound: Option<String>,
    /// How much storage there is
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<String>,
    /// A short summary
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// The website address (URL) of the item
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl PlatformVersion {
    /// The specific platform and the specifications (Xbox Series X, Playstation 5)
    pub fn new() -> PlatformVersion {
        PlatformVersion {
            id: None,
            companies: None,
            connectivity: None,
            cpu: None,
            graphics: None,
            main_manufacturer: None,
            media: None,
            memory: None,
            name: None,
            online: None,
            os: None,
            output: None,
            platform_logo: None,
            platform_version_release_dates: None,
            resolutions: None,
            slug: None,
            sound: None,
            storage: None,
            summary: None,
            url: None,
            checksum: None,
        }
    }
}

