/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// PlatformVersionReleaseDateRegionEnum : An enum of the region for the release date   1: europe   2: north_america   3: australia   4: new_zealand   5: japan   6: china   7: asia   8: worldwide   9: korea   10: brazil   
/// An enum of the region for the release date   1: europe   2: north_america   3: australia   4: new_zealand   5: japan   6: china   7: asia   8: worldwide   9: korea   10: brazil   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum PlatformVersionReleaseDateRegionEnum {
    europe = 1,
    north_america = 2,
    australia = 3,
    new_zealand = 4,
    japan = 5,
    china = 6,
    asia = 7,
    worldwide = 8,
    korea = 9,
    brazil = 10,

}

impl std::fmt::Display for PlatformVersionReleaseDateRegionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::europe => "1",
            Self::north_america => "2",
            Self::australia => "3",
            Self::new_zealand => "4",
            Self::japan => "5",
            Self::china => "6",
            Self::asia => "7",
            Self::worldwide => "8",
            Self::korea => "9",
            Self::brazil => "10",
        })
    }
}
impl Default for PlatformVersionReleaseDateRegionEnum {
    fn default() -> PlatformVersionReleaseDateRegionEnum {
        Self::europe
    }
}

