/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformVersionReleaseDate : A handy endpoint that extends platform release dates. Used to dig deeper into release dates, platforms and versions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformVersionReleaseDate {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<models::PlatformVersionReleaseDateEnums>,
    /// The IGDB object unique identifier
    #[serde(rename = "date_format", skip_serializing_if = "Option::is_none")]
    pub date_format: Option<i32>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The release date
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<i64>,
    /// A human readable version of the release date
    #[serde(rename = "human", skip_serializing_if = "Option::is_none")]
    pub human: Option<String>,
    /// The month as an integer starting at 1 (January)
    #[serde(rename = "m", skip_serializing_if = "Option::is_none")]
    pub m: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "platform_version", skip_serializing_if = "Option::is_none")]
    pub platform_version: Option<i32>,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<models::PlatformVersionReleaseDateRegionEnum>,
    /// The IGDB object unique identifier
    #[serde(rename = "release_region", skip_serializing_if = "Option::is_none")]
    pub release_region: Option<i32>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// The year in full (2018)
    #[serde(rename = "y", skip_serializing_if = "Option::is_none")]
    pub y: Option<i32>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl PlatformVersionReleaseDate {
    /// A handy endpoint that extends platform release dates. Used to dig deeper into release dates, platforms and versions.
    pub fn new() -> PlatformVersionReleaseDate {
        PlatformVersionReleaseDate {
            id: None,
            category: None,
            date_format: None,
            created_at: None,
            date: None,
            human: None,
            m: None,
            platform_version: None,
            region: None,
            release_region: None,
            updated_at: None,
            y: None,
            checksum: None,
        }
    }
}

