/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// PlatformCategoryEnums : The category of the platform   1: console   2: arcade   3: platform   4: operating_system   5: portable_console   6: computer   
/// The category of the platform   1: console   2: arcade   3: platform   4: operating_system   5: portable_console   6: computer   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum PlatformCategoryEnums {
    console = 1,
    arcade = 2,
    platform = 3,
    operating_system = 4,
    portable_console = 5,
    computer = 6,

}

impl std::fmt::Display for PlatformCategoryEnums {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::console => "1",
            Self::arcade => "2",
            Self::platform => "3",
            Self::operating_system => "4",
            Self::portable_console => "5",
            Self::computer => "6",
        })
    }
}
impl Default for PlatformCategoryEnums {
    fn default() -> PlatformCategoryEnums {
        Self::console
    }
}

