/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// PlatformWebsiteCategoryEnums : The platform website   1: official   2: wikia   3: wikipedia   4: facebook   5: twitter   6: twitch   8: instagram   9: youtube   10: iphone   11: ipad   12: android   13: steam   14: reddit   15: discord   16: google_plus   17: tumblr   18: linkedin   19: pinterest   20: soundcloud   
/// The platform website   1: official   2: wikia   3: wikipedia   4: facebook   5: twitter   6: twitch   8: instagram   9: youtube   10: iphone   11: ipad   12: android   13: steam   14: reddit   15: discord   16: google_plus   17: tumblr   18: linkedin   19: pinterest   20: soundcloud   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum PlatformWebsiteCategoryEnums {
    official = 1,
    wikia = 2,
    wikipedia = 3,
    facebook = 4,
    twitter = 5,
    twitch = 6,
    instagram = 8,
    youtube = 9,
    iphone = 10,
    ipad = 11,
    android = 12,
    steam = 13,
    reddit = 14,
    discord = 15,
    google_plus = 16,
    tumblr = 17,
    linkedin = 18,
    pinterest = 19,
    soundcloud = 20,

}

impl std::fmt::Display for PlatformWebsiteCategoryEnums {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::official => "1",
            Self::wikia => "2",
            Self::wikipedia => "3",
            Self::facebook => "4",
            Self::twitter => "5",
            Self::twitch => "6",
            Self::instagram => "8",
            Self::youtube => "9",
            Self::iphone => "10",
            Self::ipad => "11",
            Self::android => "12",
            Self::steam => "13",
            Self::reddit => "14",
            Self::discord => "15",
            Self::google_plus => "16",
            Self::tumblr => "17",
            Self::linkedin => "18",
            Self::pinterest => "19",
            Self::soundcloud => "20",
        })
    }
}
impl Default for PlatformWebsiteCategoryEnums {
    fn default() -> PlatformWebsiteCategoryEnums {
        Self::official
    }
}

