/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PopularityPrimative : Lists abailable primatives with their source and popularity type
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PopularityPrimative {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "game_id", skip_serializing_if = "Option::is_none")]
    pub game_id: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "popularity_type", skip_serializing_if = "Option::is_none")]
    pub popularity_type: Option<i32>,
    #[serde(rename = "popularity_source", skip_serializing_if = "Option::is_none")]
    pub popularity_source: Option<models::PopularityPrimitiveEnum>,
    /// The IGDB object unique identifier
    #[serde(rename = "external_popularity_source", skip_serializing_if = "Option::is_none")]
    pub external_popularity_source: Option<i32>,
    /// The rating value
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i32>,
    /// Timestamp of when the primatives were calculated
    #[serde(rename = "calculated_at", skip_serializing_if = "Option::is_none")]
    pub calculated_at: Option<i64>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
}

impl PopularityPrimative {
    /// Lists abailable primatives with their source and popularity type
    pub fn new() -> PopularityPrimative {
        PopularityPrimative {
            id: None,
            game_id: None,
            popularity_type: None,
            popularity_source: None,
            external_popularity_source: None,
            value: None,
            calculated_at: None,
            created_at: None,
            updated_at: None,
        }
    }
}

