/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PopularityType : Describes what type of popularity primative or popularity indicator the popularity indicator the popularity value is
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PopularityType {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "popularity_source", skip_serializing_if = "Option::is_none")]
    pub popularity_source: Option<models::PopularityTypeEnum>,
    /// The IGDB object unique identifier
    #[serde(rename = "external_popularity_source", skip_serializing_if = "Option::is_none")]
    pub external_popularity_source: Option<i32>,
    /// The name of the type of popularity from the source
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Date this was initially added to the IGDB database
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// The last date this entry was updated in the IGDB database
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// The IGDB object unique identifier
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl PopularityType {
    /// Describes what type of popularity primative or popularity indicator the popularity indicator the popularity value is
    pub fn new() -> PopularityType {
        PopularityType {
            id: None,
            popularity_source: None,
            external_popularity_source: None,
            name: None,
            created_at: None,
            updated_at: None,
            checksum: None,
        }
    }
}

