/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RetrieveAgeRating401Response : Authorization Failure
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveAgeRating401Response {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "Tip 1", skip_serializing_if = "Option::is_none")]
    pub tip_1: Option<String>,
    #[serde(rename = "Tip 2", skip_serializing_if = "Option::is_none")]
    pub tip_2: Option<String>,
    #[serde(rename = "Tip 3", skip_serializing_if = "Option::is_none")]
    pub tip_3: Option<String>,
    #[serde(rename = "Docs", skip_serializing_if = "Option::is_none")]
    pub docs: Option<String>,
    #[serde(rename = "Discord", skip_serializing_if = "Option::is_none")]
    pub discord: Option<String>,
}

impl RetrieveAgeRating401Response {
    /// Authorization Failure
    pub fn new() -> RetrieveAgeRating401Response {
        RetrieveAgeRating401Response {
            message: None,
            tip_1: None,
            tip_2: None,
            tip_3: None,
            docs: None,
            discord: None,
        }
    }
}

