/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Search : Search IGDB and get the IDs of items matching your search
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Search {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "alternative_name", skip_serializing_if = "Option::is_none")]
    pub alternative_name: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "character", skip_serializing_if = "Option::is_none")]
    pub character: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "collection", skip_serializing_if = "Option::is_none")]
    pub collection: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<i32>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The IGDB object unique identifier
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<i32>,
    /// The date this item was initally published by the third party
    #[serde(rename = "published_at", skip_serializing_if = "Option::is_none")]
    pub published_at: Option<i64>,
    /// Reference ID for Test Dummy
    #[serde(rename = "test_dummy", skip_serializing_if = "Option::is_none")]
    pub test_dummy: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<i32>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl Search {
    /// Search IGDB and get the IDs of items matching your search
    pub fn new() -> Search {
        Search {
            id: None,
            alternative_name: None,
            character: None,
            collection: None,
            company: None,
            description: None,
            game: None,
            name: None,
            platform: None,
            published_at: None,
            test_dummy: None,
            theme: None,
            checksum: None,
        }
    }
}

