/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// StartDateCategoryEnum : An enum of the date format   0: YYYYMMMMDD   1: YYYYMMMM   2: YYYY   3: YYYYQ1   4: YYYYQ2   5: YYYYQ3   6: YYYYQ4   7: TBD   
/// An enum of the date format   0: YYYYMMMMDD   1: YYYYMMMM   2: YYYY   3: YYYYQ1   4: YYYYQ2   5: YYYYQ3   6: YYYYQ4   7: TBD   
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum StartDateCategoryEnum {
    YYYYMMMMDD = 0,
    YYYYMMMM = 1,
    YYYY = 2,
    YYYYQ1 = 3,
    YYYYQ2 = 4,
    YYYYQ3 = 5,
    YYYYQ4 = 6,
    TBD = 7,

}

impl std::fmt::Display for StartDateCategoryEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::YYYYMMMMDD => "0",
            Self::YYYYMMMM => "1",
            Self::YYYY => "2",
            Self::YYYYQ1 => "3",
            Self::YYYYQ2 => "4",
            Self::YYYYQ3 => "5",
            Self::YYYYQ4 => "6",
            Self::TBD => "7",
        })
    }
}
impl Default for StartDateCategoryEnum {
    fn default() -> StartDateCategoryEnum {
        Self::YYYYMMMMDD
    }
}

