/*
 * IGDB API
 *
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Website : A website URL, usually associated with a game
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Website {
    /// The IGDB object unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<models::WebsiteCategoryEnums>,
    /// The IGDB object unique identifier
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    /// The IGDB object unique identifier
    #[serde(rename = "game", skip_serializing_if = "Option::is_none")]
    pub game: Option<i32>,
    #[serde(rename = "trusted", skip_serializing_if = "Option::is_none")]
    pub trusted: Option<bool>,
    /// The main platform address (URL) of the platform
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Hash of the object
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<uuid::Uuid>,
}

impl Website {
    /// A website URL, usually associated with a game
    pub fn new() -> Website {
        Website {
            id: None,
            category: None,
            r#type: None,
            game: None,
            trusted: None,
            url: None,
            checksum: None,
        }
    }
}

