/*
 * RAWG Video Games Database API
 *
 *  The largest open video games database.  ### Why build on RAWG - More than 350,000 games for 50 platforms including mobiles. - Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates, Metacritic ratings. - Where to buy: links to digital distribution services - Similar games based on visual similarity. - Player activity data: Steam average playtime and RAWG player counts and ratings. - Actively developing and constantly getting better by user contribution and our algorithms.  ### Terms of Use - Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active hyperlink from every page where the data of RAWG is used. - Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000 page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for commercial terms. - No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt, and we will talk it through. - You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs. If you don’t provide it, we may ban your requests.  __[Read more](https://rawg.io/apidocs)__. 
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Game {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "released", skip_serializing_if = "Option::is_none")]
    pub released: Option<chrono::NaiveDate>,
    #[serde(rename = "tba", skip_serializing_if = "Option::is_none")]
    pub tba: Option<bool>,
    #[serde(rename = "background_image", skip_serializing_if = "Option::is_none")]
    pub background_image: Option<String>,
    #[serde(rename = "rating")]
    pub rating: f64,
    #[serde(rename = "rating_top", skip_serializing_if = "Option::is_none")]
    pub rating_top: Option<i32>,
    #[serde(rename = "ratings", skip_serializing_if = "Option::is_none")]
    pub ratings: Option<serde_json::Value>,
    #[serde(rename = "ratings_count", skip_serializing_if = "Option::is_none")]
    pub ratings_count: Option<i32>,
    #[serde(rename = "reviews_text_count", skip_serializing_if = "Option::is_none")]
    pub reviews_text_count: Option<i32>,
    #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
    pub added: Option<i32>,
    #[serde(rename = "added_by_status", skip_serializing_if = "Option::is_none")]
    pub added_by_status: Option<serde_json::Value>,
    #[serde(rename = "metacritic", skip_serializing_if = "Option::is_none")]
    pub metacritic: Option<i32>,
    /// in hours
    #[serde(rename = "playtime", skip_serializing_if = "Option::is_none")]
    pub playtime: Option<i32>,
    #[serde(rename = "suggestions_count", skip_serializing_if = "Option::is_none")]
    pub suggestions_count: Option<i32>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<chrono::NaiveDateTime>,
    #[serde(rename = "esrb_rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub esrb_rating: Option<Option<Box<models::GameEsrbRating>>>,
    #[serde(rename = "platforms", skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<models::GamePlatformsInner>>,
}

impl Game {
    pub fn new(rating: f64) -> Game {
        Game {
            id: None,
            slug: None,
            name: None,
            released: None,
            tba: None,
            background_image: None,
            rating,
            rating_top: None,
            ratings: None,
            ratings_count: None,
            reviews_text_count: None,
            added: None,
            added_by_status: None,
            metacritic: None,
            playtime: None,
            suggestions_count: None,
            updated: None,
            esrb_rating: None,
            platforms: None,
        }
    }
}

