/*
 * RAWG Video Games Database API
 *
 *  The largest open video games database.  ### Why build on RAWG - More than 350,000 games for 50 platforms including mobiles. - Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates, Metacritic ratings. - Where to buy: links to digital distribution services - Similar games based on visual similarity. - Player activity data: Steam average playtime and RAWG player counts and ratings. - Actively developing and constantly getting better by user contribution and our algorithms.  ### Terms of Use - Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active hyperlink from every page where the data of RAWG is used. - Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000 page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for commercial terms. - No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt, and we will talk it through. - You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs. If you don’t provide it, we may ban your requests.  __[Read more](https://rawg.io/apidocs)__. 
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GameSingle {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "name_original", skip_serializing_if = "Option::is_none")]
    pub name_original: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "metacritic", skip_serializing_if = "Option::is_none")]
    pub metacritic: Option<i32>,
    #[serde(rename = "metacritic_platforms", skip_serializing_if = "Option::is_none")]
    pub metacritic_platforms: Option<Vec<models::GamePlatformMetacritic>>,
    #[serde(rename = "released", skip_serializing_if = "Option::is_none")]
    pub released: Option<chrono::NaiveDate>,
    #[serde(rename = "tba", skip_serializing_if = "Option::is_none")]
    pub tba: Option<bool>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "background_image", skip_serializing_if = "Option::is_none")]
    pub background_image: Option<String>,
    #[serde(rename = "background_image_additional", skip_serializing_if = "Option::is_none")]
    pub background_image_additional: Option<String>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    #[serde(rename = "rating")]
    pub rating: f64,
    #[serde(rename = "rating_top", skip_serializing_if = "Option::is_none")]
    pub rating_top: Option<i32>,
    #[serde(rename = "ratings", skip_serializing_if = "Option::is_none")]
    pub ratings: Option<serde_json::Value>,
    #[serde(rename = "reactions", skip_serializing_if = "Option::is_none")]
    pub reactions: Option<serde_json::Value>,
    #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
    pub added: Option<i32>,
    #[serde(rename = "added_by_status", skip_serializing_if = "Option::is_none")]
    pub added_by_status: Option<serde_json::Value>,
    /// in hours
    #[serde(rename = "playtime", skip_serializing_if = "Option::is_none")]
    pub playtime: Option<i32>,
    #[serde(rename = "screenshots_count", skip_serializing_if = "Option::is_none")]
    pub screenshots_count: Option<i32>,
    #[serde(rename = "movies_count", skip_serializing_if = "Option::is_none")]
    pub movies_count: Option<i32>,
    #[serde(rename = "creators_count", skip_serializing_if = "Option::is_none")]
    pub creators_count: Option<i32>,
    #[serde(rename = "achievements_count", skip_serializing_if = "Option::is_none")]
    pub achievements_count: Option<i32>,
    #[serde(rename = "parent_achievements_count", skip_serializing_if = "Option::is_none")]
    pub parent_achievements_count: Option<String>,
    /// For example \"https://www.reddit.com/r/uncharted/\" or \"uncharted\"
    #[serde(rename = "reddit_url", skip_serializing_if = "Option::is_none")]
    pub reddit_url: Option<String>,
    #[serde(rename = "reddit_name", skip_serializing_if = "Option::is_none")]
    pub reddit_name: Option<String>,
    #[serde(rename = "reddit_description", skip_serializing_if = "Option::is_none")]
    pub reddit_description: Option<String>,
    #[serde(rename = "reddit_logo", skip_serializing_if = "Option::is_none")]
    pub reddit_logo: Option<String>,
    #[serde(rename = "reddit_count", skip_serializing_if = "Option::is_none")]
    pub reddit_count: Option<i32>,
    #[serde(rename = "twitch_count", skip_serializing_if = "Option::is_none")]
    pub twitch_count: Option<String>,
    #[serde(rename = "youtube_count", skip_serializing_if = "Option::is_none")]
    pub youtube_count: Option<String>,
    #[serde(rename = "reviews_text_count", skip_serializing_if = "Option::is_none")]
    pub reviews_text_count: Option<String>,
    #[serde(rename = "ratings_count", skip_serializing_if = "Option::is_none")]
    pub ratings_count: Option<i32>,
    #[serde(rename = "suggestions_count", skip_serializing_if = "Option::is_none")]
    pub suggestions_count: Option<i32>,
    #[serde(rename = "alternative_names", skip_serializing_if = "Option::is_none")]
    pub alternative_names: Option<Vec<String>>,
    /// For example \"http://www.metacritic.com/game/playstation-4/the-witcher-3-wild-hunt\"
    #[serde(rename = "metacritic_url", skip_serializing_if = "Option::is_none")]
    pub metacritic_url: Option<String>,
    #[serde(rename = "parents_count", skip_serializing_if = "Option::is_none")]
    pub parents_count: Option<i32>,
    #[serde(rename = "additions_count", skip_serializing_if = "Option::is_none")]
    pub additions_count: Option<i32>,
    #[serde(rename = "game_series_count", skip_serializing_if = "Option::is_none")]
    pub game_series_count: Option<i32>,
    #[serde(rename = "esrb_rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub esrb_rating: Option<Option<Box<models::GameEsrbRating>>>,
    #[serde(rename = "platforms", skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<models::GamePlatformsInner>>,
}

impl GameSingle {
    pub fn new(rating: f64) -> GameSingle {
        GameSingle {
            id: None,
            slug: None,
            name: None,
            name_original: None,
            description: None,
            metacritic: None,
            metacritic_platforms: None,
            released: None,
            tba: None,
            updated: None,
            background_image: None,
            background_image_additional: None,
            website: None,
            rating,
            rating_top: None,
            ratings: None,
            reactions: None,
            added: None,
            added_by_status: None,
            playtime: None,
            screenshots_count: None,
            movies_count: None,
            creators_count: None,
            achievements_count: None,
            parent_achievements_count: None,
            reddit_url: None,
            reddit_name: None,
            reddit_description: None,
            reddit_logo: None,
            reddit_count: None,
            twitch_count: None,
            youtube_count: None,
            reviews_text_count: None,
            ratings_count: None,
            suggestions_count: None,
            alternative_names: None,
            metacritic_url: None,
            parents_count: None,
            additions_count: None,
            game_series_count: None,
            esrb_rating: None,
            platforms: None,
        }
    }
}

