/*
 * RAWG Video Games Database API
 *
 *  The largest open video games database.  ### Why build on RAWG - More than 350,000 games for 50 platforms including mobiles. - Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates, Metacritic ratings. - Where to buy: links to digital distribution services - Similar games based on visual similarity. - Player activity data: Steam average playtime and RAWG player counts and ratings. - Actively developing and constantly getting better by user contribution and our algorithms.  ### Terms of Use - Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active hyperlink from every page where the data of RAWG is used. - Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000 page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for commercial terms. - No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt, and we will talk it through. - You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs. If you don’t provide it, we may ban your requests.  __[Read more](https://rawg.io/apidocs)__. 
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`games_achievements_read`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesAchievementsReadError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_additions_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesAdditionsListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_development_team_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesDevelopmentTeamListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_game_series_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesGameSeriesListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_movies_read`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesMoviesReadError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_parent_games_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesParentGamesListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_read`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesReadError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_reddit_read`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesRedditReadError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_screenshots_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesScreenshotsListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_stores_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesStoresListError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_suggested_read`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesSuggestedReadError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_twitch_read`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesTwitchReadError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`games_youtube_read`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GamesYoutubeReadError {
    UnknownValue(serde_json::Value),
}


pub async fn games_achievements_read(configuration: &configuration::Configuration, id: &str) -> Result<models::ParentAchievement, Error<GamesAchievementsReadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/games/{id}/achievements", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ParentAchievement`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ParentAchievement`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesAchievementsReadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_additions_list(configuration: &configuration::Configuration, game_pk: &str, page: Option<i32>, page_size: Option<i32>) -> Result<models::GamesList200Response, Error<GamesAdditionsListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_game_pk = game_pk;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/games/{game_pk}/additions", configuration.base_path, game_pk=crate::apis::urlencode(p_path_game_pk));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GamesList200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GamesList200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesAdditionsListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_development_team_list(configuration: &configuration::Configuration, game_pk: &str, ordering: Option<&str>, page: Option<i32>, page_size: Option<i32>) -> Result<models::GamesDevelopmentTeamList200Response, Error<GamesDevelopmentTeamListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_game_pk = game_pk;
    let p_query_ordering = ordering;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/games/{game_pk}/development-team", configuration.base_path, game_pk=crate::apis::urlencode(p_path_game_pk));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_ordering {
        req_builder = req_builder.query(&[("ordering", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GamesDevelopmentTeamList200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GamesDevelopmentTeamList200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesDevelopmentTeamListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_game_series_list(configuration: &configuration::Configuration, game_pk: &str, page: Option<i32>, page_size: Option<i32>) -> Result<models::GamesList200Response, Error<GamesGameSeriesListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_game_pk = game_pk;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/games/{game_pk}/game-series", configuration.base_path, game_pk=crate::apis::urlencode(p_path_game_pk));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GamesList200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GamesList200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesGameSeriesListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_list(configuration: &configuration::Configuration, page: Option<i32>, page_size: Option<i32>, search: Option<&str>, search_precise: Option<bool>, search_exact: Option<bool>, parent_platforms: Option<&str>, platforms: Option<&str>, stores: Option<&str>, developers: Option<&str>, publishers: Option<&str>, genres: Option<&str>, tags: Option<&str>, creators: Option<&str>, dates: Option<&str>, updated: Option<&str>, platforms_count: Option<i32>, metacritic: Option<&str>, exclude_collection: Option<i32>, exclude_additions: Option<bool>, exclude_parents: Option<bool>, exclude_game_series: Option<bool>, exclude_stores: Option<&str>, ordering: Option<&str>) -> Result<models::GamesList200Response, Error<GamesListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_page = page;
    let p_query_page_size = page_size;
    let p_query_search = search;
    let p_query_search_precise = search_precise;
    let p_query_search_exact = search_exact;
    let p_query_parent_platforms = parent_platforms;
    let p_query_platforms = platforms;
    let p_query_stores = stores;
    let p_query_developers = developers;
    let p_query_publishers = publishers;
    let p_query_genres = genres;
    let p_query_tags = tags;
    let p_query_creators = creators;
    let p_query_dates = dates;
    let p_query_updated = updated;
    let p_query_platforms_count = platforms_count;
    let p_query_metacritic = metacritic;
    let p_query_exclude_collection = exclude_collection;
    let p_query_exclude_additions = exclude_additions;
    let p_query_exclude_parents = exclude_parents;
    let p_query_exclude_game_series = exclude_game_series;
    let p_query_exclude_stores = exclude_stores;
    let p_query_ordering = ordering;

    let uri_str = format!("{}/games", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    // Inject API key into query if present
    if let Some(ref param_value) = configuration.api_key {
        req_builder = req_builder.query(&[("key", &param_value.key.to_string())]);
    }

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search {
        req_builder = req_builder.query(&[("search", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search_precise {
        req_builder = req_builder.query(&[("search_precise", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search_exact {
        req_builder = req_builder.query(&[("search_exact", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_parent_platforms {
        req_builder = req_builder.query(&[("parent_platforms", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_platforms {
        req_builder = req_builder.query(&[("platforms", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_stores {
        req_builder = req_builder.query(&[("stores", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_developers {
        req_builder = req_builder.query(&[("developers", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_publishers {
        req_builder = req_builder.query(&[("publishers", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_genres {
        req_builder = req_builder.query(&[("genres", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_tags {
        req_builder = req_builder.query(&[("tags", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_creators {
        req_builder = req_builder.query(&[("creators", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_dates {
        req_builder = req_builder.query(&[("dates", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_updated {
        req_builder = req_builder.query(&[("updated", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_platforms_count {
        req_builder = req_builder.query(&[("platforms_count", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_metacritic {
        req_builder = req_builder.query(&[("metacritic", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_collection {
        req_builder = req_builder.query(&[("exclude_collection", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_additions {
        req_builder = req_builder.query(&[("exclude_additions", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_parents {
        req_builder = req_builder.query(&[("exclude_parents", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_game_series {
        req_builder = req_builder.query(&[("exclude_game_series", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_stores {
        req_builder = req_builder.query(&[("exclude_stores", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_ordering {
        req_builder = req_builder.query(&[("ordering", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GamesList200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GamesList200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_movies_read(configuration: &configuration::Configuration, id: &str) -> Result<models::Movie, Error<GamesMoviesReadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/games/{id}/movies", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Movie`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Movie`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesMoviesReadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_parent_games_list(configuration: &configuration::Configuration, game_pk: &str, page: Option<i32>, page_size: Option<i32>) -> Result<models::GamesList200Response, Error<GamesParentGamesListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_game_pk = game_pk;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/games/{game_pk}/parent-games", configuration.base_path, game_pk=crate::apis::urlencode(p_path_game_pk));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GamesList200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GamesList200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesParentGamesListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_read(configuration: &configuration::Configuration, id: &str) -> Result<models::GameSingle, Error<GamesReadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/games/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GameSingle`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GameSingle`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesReadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_reddit_read(configuration: &configuration::Configuration, id: &str) -> Result<models::Reddit, Error<GamesRedditReadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/games/{id}/reddit", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Reddit`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Reddit`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesRedditReadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_screenshots_list(configuration: &configuration::Configuration, game_pk: &str, ordering: Option<&str>, page: Option<i32>, page_size: Option<i32>) -> Result<models::GamesScreenshotsList200Response, Error<GamesScreenshotsListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_game_pk = game_pk;
    let p_query_ordering = ordering;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/games/{game_pk}/screenshots", configuration.base_path, game_pk=crate::apis::urlencode(p_path_game_pk));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_ordering {
        req_builder = req_builder.query(&[("ordering", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GamesScreenshotsList200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GamesScreenshotsList200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesScreenshotsListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_stores_list(configuration: &configuration::Configuration, game_pk: &str, ordering: Option<&str>, page: Option<i32>, page_size: Option<i32>) -> Result<models::GamesStoresList200Response, Error<GamesStoresListError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_game_pk = game_pk;
    let p_query_ordering = ordering;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/games/{game_pk}/stores", configuration.base_path, game_pk=crate::apis::urlencode(p_path_game_pk));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_ordering {
        req_builder = req_builder.query(&[("ordering", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GamesStoresList200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GamesStoresList200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesStoresListError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_suggested_read(configuration: &configuration::Configuration, id: &str) -> Result<models::GameSingle, Error<GamesSuggestedReadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/games/{id}/suggested", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GameSingle`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GameSingle`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesSuggestedReadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_twitch_read(configuration: &configuration::Configuration, id: &str) -> Result<models::Twitch, Error<GamesTwitchReadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/games/{id}/twitch", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Twitch`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Twitch`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesTwitchReadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn games_youtube_read(configuration: &configuration::Configuration, id: &str) -> Result<models::Youtube, Error<GamesYoutubeReadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/games/{id}/youtube", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Youtube`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Youtube`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GamesYoutubeReadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

